controller_manager:
  ros__parameters:
    update_rate: 150  # Hz

    # Joint State Broadcaster (publishes states for all joints)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # xArm6 Trajectory Controller
    xarm6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# xArm6 Trajectory Controller params
xarm6_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 1.0, goal: 0.02}
      joint2: {trajectory: 1.0, goal: 0.02}
      joint3: {trajectory: 1.0, goal: 0.02}
      joint4: {trajectory: 1.0, goal: 0.02}
      joint5: {trajectory: 1.0, goal: 0.02}
      joint6: {trajectory: 1.0, goal: 0.02}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0