# Goal: The sequence of poses for the arm to follow
geometry_msgs/Pose[] poses
---
# Result: True if the entire path was executed successfully
bool success
string message
---
# Feedback: The index of the waypoint currently being executed
int32 waypoint_index